name: a6_birthday
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_animator: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/rute/x3/rute.right.png
    - images/rute/x2/rute.right.png
    - images/rute/x3/rute.left.png
    - images/rute/x2/rute.left.png
    - images/rute/x3/rute.right.legUp1.png
    - images/rute/x2/rute.right.legUp1.png
    - images/rute/x3/rute.left.legUp1.png
    - images/rute/x2/rute.left.legUp1.png
    - images/rute/x3/rute.right.legUp2.png
    - images/rute/x2/rute.right.legUp2.png
    - images/rute/x3/rute.left.legUp2.png
    - images/rute/x2/rute.left.legUp2.png
    - images/rute/x3/rute.left.openDoor.png
    - images/scenario/menu4.png
    - images/scenario/livingRoom.png
    - images/scenario/ruaJacobina.png
    - images/scenario/level.one.arrow.png
    - images/scenario/levelTwo.png
    - images/scenario/levelThree.png
    - images/scenario/levelFour.png
    - images/rute/x2/rute.left.running1.png
    - images/rute/x2/rute.left.running2.png
    - images/rute/x2/rute.right.running1.png
    - images/rute/x2/rute.right.running2.png
    - images/rute/x2/rute.swimming.left.png
    - images/rute/x2/rute.swimming.left1.png
    - images/rute/x2/rute.swimming.left2.png
    - images/rute/x2/rute.swimming.right.png
    - images/rute/x2/rute.swimming.right1.png
    - images/rute/x2/rute.swimming.right2.png
    - images/scenario/level.two.arrow.png
    - images/scenario/level.three.arrow.png
    - images/rute/x2/rute.biking.right.png
    - images/rute/x2/rute.right.biking1.png
    - images/rute/x2/rute.biking.left.png
    - images/rute/x2/rute.left.biking1.png
    - images/rute/x2/bike.png
    - images/familia/familia.png
    - images/rute/x2/rute.right.smiling.png
    - images/rute/x2/rute.right.legUp1.smiling.png
    - images/rute/x2/rute.right.legUp2.smiling.png
    - images/rute/x2/rute.left.smiling.png
    - images/rute/x2/rute.left.legUp1.smiling.png
    - images/rute/x2/rute.left.legUp2.smiling.png

    
  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
